### PR TITLE
Feature/6 openid login

### PR DESCRIPTION
**Pull request by WGierke**
This pull request implements the demands of ticket #6 
- It is now possible to register and log in via OpenID
- If the OpenID provider passes no email address when the user wants to register, the user is registered and requested to enter a valid one. Until that happens, he can't perform any actions.
- added Schema information to models
- moved code from db/seeds to new rake task so only mandatory default values can be placed in the db/seeds file (updated README about that, too)
- added flash messages and a rudimentary user profile
- removed unnecessary code that was automatically created by the Rails generator
- refactored dev branch

We would be glad about any comments, suggestions or just "Thumps-Ups (:+1:)" :)

### CODE REVIEW

**Comment by threxx** [comment]
:+1: „smile“-Emoticon

**Comment by WGierke** [comment]
@hpi-swt2/team-fp @hpi-swt2/team-jn @hpi-swt2/team-mk ping

**Comment by arneboockmeyer** [comment]
Du hast in diesem PR auch Code von anderen Features refactored? Könntest du das in einen eigenen PR umziehen?

**Comment by WGierke** [comment]
Done:
[zum Holiday Leave Merge](https://github.com/hpi-swt2/wimi-portal/pull/81)
[zum Dashboard Merge](https://github.com/hpi-swt2/wimi-portal/pull/82)

**Comment by arneboockmeyer** [comment]
@WGierke please solve conflicts

**Comment by WGierke** [comment]
@arneboockmeyer Done..

**Comment by arneboockmeyer** [comment]
@WGierke sure? this PR is still not mergeable

**Comment by WGierke** [comment]
It was ready until the next one merged in dev. Give me a sec ...

**Comment by WGierke** [comment]
@arneboockmeyer Done. Please review and merge it quickly otherwise the dev has to be merged a fifth time ...

**Pull request merged**
