### PR TITLE
Refactor/code linting

### PR DESCRIPTION
**Pull request by WGierke**
@hpi-swt2/team-fp @hpi-swt2/team-jn @hpi-swt2/team-mk 

I used Rubocop to style the code according to the [Rails Styleguide](https://github.com/bbatsov/rails-style-guide).

### Functional improvements
- use count instead of select...size
- use find instead of select...first
- by prepending & to a symbol you create a lambda function that calls the method with the name of the symbol on the object  
Example:  
 `users.select(&:is_wimi?)`  
equals `users.select( users.map { |user| user.is_wimi? })`  
equals `users.select { |u| u.is_wimi? } ` (which was used until now)

### Indentation and alignment  
- Indentation: use 2 spaces, no tabs
- Don't indent after private
- Use 2 spaces for indentation in an array, relative to the start of the line where the left bracket is
- Align the elements of an array literal if they span more than one line
- Surround operator '-',  '+' and '<<' with spaces
- Missing Space after colon and comma
- Spaces inside {
- Only 1 linebreak between two functions 

### Other stuff
- Prefer single-quoted strings when you don't need string interpolation or special symbols.
- Redundant self and return statements
- Not necessary to use brackets around if-conditions
- Prefer ! over not since it has a higher priority:  
!true && false  
=> false  
not true && false  
=> true

Please have a look at it (although the Travis test currently errors due to some server issues).

### CODE REVIEW

**Comment by tbjoern** [comment]
LGTM :+1: Danke fuer den Aufwand !

**Comment by bahnfahren** [comment]
Auch von mir vielen Dank!
Könntest du, Willi, den dev bei dir reinmengen damit keine Konflikte entstehen - das darauffolgende wieder in den dev mergen kannst du dann ja automatisch noch hinterher machen :)

**Comment by threxx** [comment]
LGTM

**Comment by arneboockmeyer** [comment]
Please solve merge conflicts

**Comment by WGierke** [comment]
@arneboockmeyer Done. Thanks @tbjoern @bahnfahren @threxx for your reviews, I'll merge in dev now :)

**Pull request merged**
